[package]
name = "stackyzdev/loader"
description = "Requires all modules within a given instance"
version = "2.0.1"
license = "MIT"
authors = ["Stephen Leitnick", "StackyzDev"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
